### ISSUE TITLE
add plugin to redmine.org plugin repo

### ISSUE THREAD

**Issue by tofi86** [mediatainment/redmine_codebutton#1]
Hey,
it would be very nice if you could add the plugin to the redmine.org plugin repository at http://www.redmine.org/plugins

I can confirm that it works well with redmine 2.4.x

cheers,
toby

**Comment by tofi86** [comment]
This should be re-opened, as you have to rename the plugin on redmine.org as described above!
Just edit your plugin entry http://www.redmine.org/plugins/codehightlight_button and change the identifier to `redmine_codebutton`

**Comment by tofi86** [comment]
Hey Jan, can you probably update the redmine.org plugin repo entry accordingly?

* changing the plugin identifier to `redmine_codebutton`
* adding version 0.3.0 and Redmine 3.4 support

Thanks! 👍

**Comment by exocode** [comment]
If you make a pull request I will merge! I am not using Redmond’s since a while, so I am not maintaining this plug, but accepting PRs :-)

Best regards
